### ISSUE TITLE
[0.15.2] Cannot run `bat` with argument

### ISSUE THREAD

**Issue by dpacbach** [sharkdp/bat#1022]
**What version of `bat` are you using?**
0.15.2

Problem does not occur with version 0.15.0 which is the last version I tried.

**Describe the bug you encountered:**
```
$ bat somefile.sh
main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/rustc-1.41.0/src/libcore/macros/mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Describe what you expected to happen?**
Displays contents of file.

**How did you install `bat`?**
Cloned repo, checked out v0.15.2, built with cargo.

system
------

**$ uname -srm**
Linux 5.0.0-25-generic x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID: LinuxMint  
Description:    Linux Mint 19.1 Tessa  
Release:        19.1  
Codename:       tessa  

bat
---

**$ bat --version**
bat 0.15.2  

```

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.
No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (GNU regular expressions)

**Comment by mariopal** [comment]
I just installed rustup and then bat on my Debian Sid, and I have the same problem.

**Comment by panicst8** [comment]
I just installed with: cargo install bat 

operating system: centOS 7
ran with: RUST_BACKTRACE=full bat Dockerfile

received same error as above:

   0:     0x55f6e13229bd - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55f6e13229bd - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55f6e13229bd - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55f6e13229bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55f6e128975c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55f6e13222a1 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x55f6e1321e55 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55f6e1321e55 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55f6e1321e55 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x55f6e13213ea - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x55f6e13213ea - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x55f6e1320f88 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55f6e1287260 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:     0x55f6e128707c - core::panicking::panic::h8a9eda1e10298363
                               at src/libcore/panicking.rs:52
  14:     0x55f6e122d29e - bat::printer::InteractivePrinter::new::h7a3b37155b097b39
  15:     0x55f6e122289d - bat::controller::Controller::run::h7958727e995be46f
  16:     0x55f6e11a4a66 - bat::run_controller::hf9557666389c3a92
  17:     0x55f6e11addc2 - bat::run::h24c3653926264f6f
  18:     0x55f6e11af294 - bat::main::h7e0d33aa93e4caaa
  19:     0x55f6e117a7b3 - std::rt::lang_start::{{closure}}::hc12ad5ff5be8e7f0
  20:     0x55f6e11af886 - main
  21:     0x7fe1ff5ef555 - __libc_start_main
  22:     0x55f6e1179ef4 - <unknown>
  23:                0x0 - <unknown>

**Comment by sharkdp** [comment]
Oh wow. Thank you for reporting this. I missed this because it does not happen in debug mode - so all the tests passed (see #1019).

This is due to the new path-absolutize/path-dedot dependency. A similar bug has been reported recently by @ignatenkobrain. But even the new 1.2.4 version of path-dedot leads to a failed `unwrap` call in this line: https://github.com/magiclen/path-dedot/blob/e82359110dc0a35a723462890756603f9fce7296/src/cwd.rs#L58

I will put out a new `bat` release as soon as possible.

**Comment by sharkdp** [comment]
This has been fixed in [v0.15.3](https://github.com/sharkdp/bat/releases/tag/v0.15.3)

**Comment by hosamaly** [comment]
Thanks for fixing this issue!

It would be great if you could update the [formula on Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb).
(I would've updated it myself but I don't know how to [update the bottle](https://github.com/Homebrew/homebrew-core/commit/431d61c038a6516516f21a6b8c4528f684371bdb).)

**Comment by sharkdp** [comment]
This is not in my "responsibility". Usually, Homebrew is very fast with upgrading to the latest version.

**Comment by hosamaly** [comment]
Thanks, @sharkdp. I'll raise the issue with Homebrew.

Thank you for the great tool 🥇

**Comment by sharkdp** [comment]
see https://github.com/Homebrew/homebrew-core/pull/55314
